<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.Cms)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: common/Cms.proto
 *
 * -*- magic methods -*-
 *
 * @method string getPageId()
 * @method void setPageId(\string $value)
 * @method string getTitle()
 * @method void setTitle(\string $value)
 * @method string getIdentifier()
 * @method void setIdentifier(\string $value)
 * @method string getContent()
 * @method void setContent(\string $value)
 */
class Cms extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.common.Cms)
  
  /**
   * @var string $page_id
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $page_id;
  
  /**
   * @var string $title
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $title;
  
  /**
   * @var string $identifier
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $identifier;
  
  /**
   * @var string $content
   * @tag 4
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $content;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.common.Cms)

  // @@protoc_insertion_point(class_scope:.service.message.common.Cms)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "page_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "title",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "identifier",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "content",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.Cms)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
