<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.ReceiveCouponRequest)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: core/ReceiveCouponRequest.proto
 *
 * -*- magic methods -*-
 *
 * @method string getRuleId()
 * @method void setRuleId(\string $value)
 */
class ReceiveCouponRequest extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.common.ReceiveCouponRequest)
  
  /**
   * @var string $rule_id
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $rule_id;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.common.ReceiveCouponRequest)

  // @@protoc_insertion_point(class_scope:.service.message.common.ReceiveCouponRequest)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "rule_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.ReceiveCouponRequest)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
