<?php
namespace service\message\common;

// @@protoc_insertion_point(namespace:.service.message.common.UpdateCartItems)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: common/UpdateCartItems.proto
 *
 * -*- magic methods -*-
 *
 * @method string getWholesalerId()
 * @method void setWholesalerId(\string $value)
 * @method string getProductId()
 * @method void setProductId(\string $value)
 * @method string getNum()
 * @method void setNum(\string $value)
 */
class UpdateCartItems extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.service.message.common.UpdateCartItems)
  
  /**
   * @var string $wholesaler_id
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $wholesaler_id;
  
  /**
   * @var string $product_id
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $product_id;
  
  /**
   * @var string $num
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $num;
  
  
  // @@protoc_insertion_point(properties_scope:.service.message.common.UpdateCartItems)

  // @@protoc_insertion_point(class_scope:.service.message.common.UpdateCartItems)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "wholesaler_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "product_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "num",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.service.message.common.UpdateCartItems)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
